/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-fixed-dim": "#44ddc1",
              "on-primary": "#ffffff",
              "on-tertiary": "#ffffff",
              "tertiary-fixed-dim": "#ffb1c1",
              "surface-tint": "#4355b9",
              "secondary-container": "#68fadd",
              "surface-dim": "#dbd9e2",
              "on-secondary": "#ffffff",
              "surface": "#fbf8ff",
              "on-tertiary-fixed-variant": "#8f003f",
              "on-surface-variant": "#454652",
              "error": "#ba1a1a",
              "on-primary-fixed-variant": "#293ca0",
              "primary": "#24389c",
              "primary-fixed-dim": "#bac3ff",
              "surface-container-high": "#e9e7f0",
              "outline-variant": "#c5c5d4",
              "surface-container": "#efedf6",
              "tertiary": "#88003b",
              "background": "#fbf8ff",
              "on-primary-container": "#cacfff",
              "secondary": "#006b5c",
              "surface-container-low": "#f4f2fc",
              "inverse-primary": "#bac3ff",
              "on-error": "#ffffff",
              "surface-variant": "#e3e1ea",
              "surface-bright": "#fbf8ff",
              "on-secondary-fixed": "#00201a",
              "on-secondary-container": "#007261",
              "surface-container-lowest": "#ffffff",
              "on-primary-fixed": "#00105c",
              "primary-container": "#3f51b5",
              "inverse-on-surface": "#f2eff9",
              "on-background": "#1a1b22",
              "secondary-fixed": "#68fadd",
              "primary-fixed": "#dee0ff",
              "surface-container-highest": "#e3e1ea",
              "on-surface": "#1a1b22",
              "tertiary-fixed": "#ffd9df",
              "on-tertiary-fixed": "#3f0018",
              "inverse-surface": "#2f3037",
              "on-tertiary-container": "#ffc3ce",
              "error-container": "#ffdad6",
              "outline": "#757684",
              "on-error-container": "#93000a",
              "on-secondary-fixed-variant": "#005145",
              "tertiary-container": "#b40050"
      },
      "fontFamily": {
              "headline": ["Manrope", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
